return {
  "mrjones2014/smart-splits.nvim",
  keys = {
    {
      "<C-k>",
      function()
        require("smart-splits").move_cursor_up()
      end,
    },
    {
      "<C-j>",
      function()
        require("smart-splits").move_cursor_down()
      end,
    },
    {
      "<C-h>",
      function()
        require("smart-splits").move_cursor_left()
      end,
    },
    {
      "<C-l>",
      function()
        require("smart-splits").move_cursor_right()
      end,
    },
    {
      "<A-k>",
      function()
        require("smart-splits").resize_up(3)
      end,
    },
    {
      "<A-j>",
      function()
        require("smart-splits").resize_down(3)
      end,
    },
    {
      "<A-h>",
      function()
        require("smart-splits").resize_left(3)
      end,
    },
    {
      "<A-l>",
      function()
        require("smart-splits").resize_right(3)
      end,
    },
    {
      "<leader><leader>k",
      function()
        require("smart-splits").swap_buf_up()
      end,
    },
    {
      "<leader><leader>j",
      function()
        require("smart-splits").swap_buf_down()
      end,
    },
    {
      "<leader><leader>h",
      function()
        require("smart-splits").swap_buf_left()
      end,
    },
    {
      "<leader><leader>l",
      function()
        require("smart-splits").swap_buf_right()
      end,
    },
  },
}
