include(${CMAKE_CURRENT_LIST_DIR}/common.cmake)

# RelWithDebInfo configuration
set(HPX_WITH_PARCELPORT_ACTION_COUNTERS ON CACHE BOOL "")
set(HPX_WITH_THREAD_IDLE_RATES ON CACHE BOOL "")
set(HPX_WITH_TESTS ON CACHE BOOL "")
set(HPX_WITH_EXAMPLES ON CACHE BOOL "")

set(HPX_WITH_PAPI ON CACHE BOOL "")
