export FERN="$PROJECTS/`\ls $PROJECTS | \grep -i \"^fern$\"`"


basename=`basename $FERN`
PATH="$FERN/environment/script:$PATH"

if [[ $OSTYPE == "cygwin" ]]; then
    PYTHONPATH="`cygpath -m $OBJECTS`/$basename/bin;$PYTHONPATH"
else
    PYTHONPATH="$OBJECTS/$basename/bin:$PYTHONPATH"
fi

unset basename


FERN_CMAKE_ARGUMENTS="
    -DPEACOCK_PREFIX:PATH=$PEACOCK_PREFIX/fern
    -DFERN_BUILD_ALGORITHM:BOOL=TRUE
    -DFERN_BUILD_DATA_MODEL:BOOL=TRUE
    -DFERN_BUILD_IO:BOOL=TRUE
    -DFERN_IO_WITH_HDF5:BOOL=TRUE
    -DFERN_IO_WITH_GDAL:BOOL=TRUE
    -DFERN_IO_WITH_GPX:BOOL=TRUE
    -DFERN_IO_WITH_NETCDF:BOOL=TRUE
    -DFERN_BUILD_LANGUAGE:BOOL=TRUE
    -DFERN_LANGUAGE_WITH_INTERPRETER:BOOL=TRUE
    -DFERN_LANGUAGE_WITH_COMPILER:BOOL=TRUE
    -DFERN_BUILD_PYTHON:BOOL=TRUE
    -DFERN_BUILD_DOCUMENTATION:BOOL=TRUE
    -DFERN_BUILD_TEST:BOOL=TRUE
"
# HPX development.
FERN_CMAKE_ARGUMENTS="
    -DPEACOCK_PREFIX:PATH=$PEACOCK_PREFIX/fern
    -DFERN_BUILD_ALGORITHM:BOOL=TRUE
    -DFERN_ALGORITHM_WITH_HPX:BOOL=TRUE
    -DFERN_BUILD_DOCUMENTATION:BOOL=TRUE
    -DFERN_BUILD_TEST:BOOL=TRUE
"
# Algorithms.
FERN_CMAKE_ARGUMENTS="
    -DPEACOCK_PREFIX:PATH=$PEACOCK_PREFIX/fern
    -DFERN_BUILD_ALGORITHM:BOOL=TRUE
    -DFERN_BUILD_DOCUMENTATION:BOOL=TRUE
    -DFERN_BUILD_TEST:BOOL=TRUE
"
# # Python extension.
# FERN_CMAKE_ARGUMENTS="
#     -DPEACOCK_PREFIX:PATH=$PEACOCK_PREFIX/fern
#     -DFERN_BUILD_PYTHON:BOOL=TRUE
#     -DFERN_BUILD_DOCUMENTATION:BOOL=TRUE
#     -DFERN_BUILD_TEST:BOOL=TRUE
# "
# FERN_CMAKE_ARGUMENTS="
#     -DPEACOCK_PREFIX:PATH=$PEACOCK_PREFIX/fern
#     -DFERN_BUILD_DATA_MODEL:BOOL=TRUE
#     -DFERN_BUILD_DOCUMENTATION:BOOL=TRUE
#     -DFERN_BUILD_TEST:BOOL=TRUE
# "


# # TODO This version of make must be used when compiling with mingw. It is
# #      not dependent on OSTYPE, but on CC.
# if [[ $OSTYPE == "cygwin" ]]; then
#     FERN_CMAKE_ARGUMENTS="
#         $FERN_CMAKE_ARGUMENTS
#         -DCMAKE_MAKE_PROGRAM:STRING=mingw32-make
#     "
# fi

if [[ $CC == "cl" ]]; then
    FERN_CMAKE_ARGUMENTS="
        $FERN_CMAKE_ARGUMENTS
        -DCMAKE_MAKE_PROGRAM:STRING=C:/utils/make
    "
fi


export FERN_CMAKE_ARGUMENTS
export PATH
export PYTHONPATH


cd $FERN

# Since there is a command named fern, we need to get rid of the alias.
unalias fern 2>/dev/null

# cd source/fern
pwd
