include(${CMAKE_CURRENT_LIST_DIR}/common.cmake)

# RelWithDebInfo configuration
set(HPX_WITH_THREAD_IDLE_RATES ON CACHE BOOL "")
set(HPX_WITH_TESTS ON CACHE BOOL "")
set(HPX_WITH_EXAMPLES ON CACHE BOOL "")
set(HPX_WITH_APEX ON CACHE BOOL "")
set(HPX_APEX_WITH_OTF2 ON CACHE BOOL "")
### set(HPX_WITH_GOOGLE_PERFTOOLS ON CACHE BOOL "")
set(HPX_WITH_PAPI ON CACHE BOOL "")
