include(${CMAKE_CURRENT_LIST_DIR}/common.cmake)

# Debug configuration
set(HPX_WITH_PARCELPORT_ACTION_COUNTERS OFF CACHE BOOL "")
set(HPX_WITH_THREAD_IDLE_RATES OFF CACHE BOOL "")
set(HPX_WITH_TESTS ON CACHE BOOL "")
set(HPX_WITH_EXAMPLES ON CACHE BOOL "")

set(HPX_WITH_APEX OFF CACHE BOOL "")
set(HPX_WITH_PAPI OFF CACHE BOOL "")
